### ISSUE TITLE
Automatic dependency update for Conan

### ISSUE THREAD

**Issue by Latios96** [Latios96/crayg#93]
- [ ] Create a script that checks for newer versions of dependencies and updates them
- [ ] Create a Github Actions workflow that runs this script and creates PRs

Multiple strategies to choose the package to update should be possible, Should be configured via YAML.

Strategies: 
- latest
- major
- minor
- patch
- never

Example YAML:

```yml

default_strategy: minor

package_strategy:
  fmt: latest
  spdlog: latest
  boost: latest

inform_about_newer_versions_than_resolved: yes # make a comment in PR
```
